### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by fallbernana123456** [IDEA-Research/Rex-Omni#18]
My GPU is 16GB. However, if the input image is small, it is normal. If it is large, it will cause CUDA out of memory. Is there any way to reduce GPU usage? For example, placing temporarily unused weights on disk or memory, etc

**Comment by Mountchicken** [comment]
There are two solutions.

- The first is to reduce the input resolution of rex-omni like this:
```
rex_model = RexOmniWrapper(
        model_path=model_path,
        backend="transformers",  # or "vllm" for faster inference
        max_tokens=4096,
        max_pixels: int = 1280 * 28 * 28,
    )
```
and reducing the resolution won’t cause a significant performance loss.

- The second is, if you’re using vllm as the backend, you can adjust parameter `gpu_memory_utilization`.
```
rex_model = RexOmniWrapper(
        model_path=model_path,
        backend="vllm",  # or "vllm" for faster inference
        gpu_memory_utilization=0.5, # the lower the less GPU mermory usage
    )
```

**Comment by fallbernana123456** [comment]
> 1280

Great, I solved the problem using the first method. Thank you for your contribution, its effect is currently the best I know.
